### ISSUE TITLE
Jekyll sources in a subdirectory seems to fail

### ISSUE THREAD

**Issue by sylvainmetayer** [ivantsepp/jekyll-git_metadata#24]
Hello,

First, thanks a lot for your work on this Gem, that is very useful. 

I'm using it in my [Jekyll blog](https://github.com/sylvainmetayer/sylvainmetayer/) and I'm currently working on the architecture of my blog, trying to put it in a subdirectory (`www`). This is a WIP and you can find my work [here](https://github.com/sylvainmetayer/sylvainmetayer/tree/feature/architecture) with the updated `config.yml`

I'm facing an issue with your plugin, which throw me this error `NoMethodError: undefined method [] for nil:NilClass` that I don't really understand. You can find below the output of the `bundle exec jekyll build --config _config.yml,_config-dev.yml --draft --trace --verbose` command.

```
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
  Logging at level: debug
Configuration file: _config.yml
Configuration file: _config-dev.yml
         Requiring: /home/ocyhc/Documents/git/sylvainmetayer.github.io/www/_plugins/environnment_variables.rb
            Source: ./www
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
           Reading: _posts/2017-06-30-tetris.md
           Reading: _posts/2018-02-20-machine-learning.md
           Reading: _posts/2017-03-28-parthenay.md
           Reading: _posts/2016-12-02-nuit-info.md
           Reading: _posts/2016-06-18-gemao.md
           Reading: _posts/2018-09-15-ansible.md
           Reading: _posts/2018-11-18-ajout-commentaires.md
           Reading: _posts/2018-02-14-tbm-interruption.md
           Reading: _posts/2018-09-30-pong.md
           Reading: _posts/2016-06-20-memoire-dut.md
           Reading: _posts/2018-11-01-latex-starterkit.md
           Reading: _posts/2018-03-30-telegram-bot.md
           Reading: _posts/2018-05-20-expert-system.md
           Reading: _posts/2016-03-18-pygame.md
           Reading: _posts/2017-01-01-macbernik.md
           Reading: _posts/2017-01-20-agent-ready.md
           Reading: _posts/2018-11-30-jekyll-gem-svg-fontawesome.md
           Reading: _posts/2015-12-01-betisier.md
           Reading: _posts/2015-05-01-bataille-navale.md
           Reading: _posts/2017-02-01-atos.md
           Reading: _posts/2018-11-15-site-personnel-v2.md
           Reading: _posts/2017-07-07-semaine-innnovante-dawin.md
           Assets:  messaging hooks on before_merge through config
           Assets:  messaging hooks on before_init through env
           Assets:  messaging hooks on after_init through env
bundler: failed to load command: jekyll (/home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/bin/jekyll)
NoMethodError: undefined method `[]' for nil:NilClass
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:71:in `page_data'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:45:in `block in load_git_metadata'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:39:in `each'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:39:in `load_git_metadata'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:13:in `block in generate'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:12:in `chdir'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-git_metadata-0.2.0/lib/jekyll/git_metadata/generator.rb:12:in `generate'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:175:in `block in generate'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `each'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `generate'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:70:in `process'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/bin/jekyll:23:in `load'
  /home/ocyhc/Documents/git/sylvainmetayer.github.io/vendor/bundle/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
```

I've ran `git remote -v` both on my git repository and the `www` folder, and the output is the same.

```
[~/Documents/git/sylvainmetayer.github.io]: (feature/architecture)$ git remote -v
origin	git@github.com:sylvainmetayer/sylvainmetayer.git (fetch)
origin	git@github.com:sylvainmetayer/sylvainmetayer.git (push)
[~/Documents/git/sylvainmetayer.github.io]: (feature/architecture)$ cd www/
[~/Documents/git/sylvainmetayer.github.io/www]: (feature/architecture)$ git remote -v
origin	git@github.com:sylvainmetayer/sylvainmetayer.git (fetch)
origin	git@github.com:sylvainmetayer/sylvainmetayer.git (push)
[~/Documents/git/sylvainmetayer.github.io/www]: (feature/architecture)$ 
```

**Comment by sylvainmetayer** [comment]
Sorry, I didn't saw that this was a duplicate of #21. Feel free to close this issue and continue on the other one !
